### ISSUE TITLE
Levels proceed after death.

### ISSUE THREAD

**Issue by nidhhoggr** [Ralex86/Goldigger#2]
Hey there, pretty cool game you got here. I made a PR with CMAKE build SLD finder as well as code formatting. I had to do this to get started and I am really interested in adding features and levels to this game but would like to get that PR merged. Please take a look and let me know if you disagree with anything. The next thing I wanted to work on was preventing level proceeding when you die and defining death, because it seems like you can just walk of the level in some screens. Others when you drop the dynamite and blows a hole in the floor, if you fall through the floor you go to the next level. I would rather it keep track of life remaining etc. Let me know if you would like to collaborate otherwise I'll just gladly work on my own work if you don't mind.

**Comment by Ralex86** [comment]
Hi,

I don't have any experience with github at all... Is there a way I give you pull privileges ?? Do whatever you want to improve the game ! As I wrote on my youtube video : "It's only a student project, its main purpose was to teach us how to properly allocate dynamic memory and that's why we used C. We also had to do modular programming where we failed wonderfully well in this project..."

**Comment by nidhhoggr** [comment]
No problem. I added PR #3 see if your can figure out how to merge it into master, it whould be pretty simple. but you might want to check out my version and test it. As far as granting me permission to work on your fork, I am not sure github works like that.

**Comment by Ralex86** [comment]
not sure how this cmake does work... I have to check if this thing is still compiling on os x

**Comment by Ralex86** [comment]
![capture d ecran 2017-01-04 a 22 43 10](https://cloud.githubusercontent.com/assets/24508644/21660334/40c622b0-d2cf-11e6-8cda-a61aff02f120.png)

Ok I've installed cmake... the game compiled and I even died touching a snake. I've also noticed the ouch sound while touching a snake ! Awesome :-)

**Comment by nidhhoggr** [comment]
Good stuff. Feel free to put together a TODO list or create some git issues and I can work on some of them in my free time and merge them in. here is a quick list I have off the top of my head:

1. level should only proceed if you pass the portal for that level
2. provide ability to kill enemies
3. maybe add a few more enemies
4. change level mapping system to varchar instead of decimal
5. Add SDL_ttf with progress indicators

**Comment by Ralex86** [comment]
Ok I hope I can work on this project again in my spare time...

todo list : 
1. use the original sprite sheet of golddigger lost mine (why not ?)
2. work on Dijkstra's algorithm for IA path finding => list, binary tree
3. implement the grappling hook feature of the original game : you can throw a grapple, hook a ledge and climb the rope...
4. find a clever way to check for ledge/floor destruction when using a dynamite (If I remember correctly I've used a double loop)

 
[PICT ID = 128 from Gold D-2.pdf](https://github.com/Ralex86/Goldigger/files/686078/PICT.ID.128.from.Gold.D-2.pdf)

**Comment by Ralex86** [comment]
![pict id 128 from gold d-2](https://cloud.githubusercontent.com/assets/24508644/21662868/c28dce3a-d2dc-11e6-88e1-73dc927f38dd.jpg)

**Comment by nidhhoggr** [comment]
Can you explain how many different entities are on there and what there purpose is? I think moving forward if we intend on adding anymore objects in the game i.e. (ledges, man, snake, gold, fire, bomb, etc..) We make isolate all their activities (initialization, rendering etc) in separate files, this way we can reduce the amount of clutter in the  GameSDL and GameState.c, in turn we can get rid of the MapObject modules because it seems to couple all of the objects into one file which will become a monster if we add all the different objects in the sprite above. 

Also, I like the concept of the level file but as mentioned in my list above will need to come up with a different system for representing the objects. I think Unicode Block with the exception of CO controls would be the simplest (complete list here) http://www.unicode.org/charts/PDF/U0000.pdf

**Comment by nidhhoggr** [comment]
PR #4 should close this issue. I'd like to get the remaining comments beyond on the scope of the issue into separate issues.
