### ISSUE TITLE
Ability to kill enemies.

### ISSUE THREAD

**Issue by nidhhoggr** [Ralex86/Goldigger#5]
Currently we have a man and a snake. I was thinking about adding a punch feature or some other sort of weapon to actually kill the enemy. And maybe the enemy should make a sound when it dies.

**Comment by Ralex86** [comment]
what about a whip ? have to find a spritesheet ...
by the way srry I don't have time yet to work on this project ! Engineer school is pretty intense for me right now. Currently trying to get my bachelor degree in applied math...

**Comment by nidhhoggr** [comment]
Yeah, anything sounds good, I was considering jumping on them like mario (which could be another option) but a weapon will make it more interesting. Good luck with those classes, I just finished my bachelors in software development. But now I have to learn all the cool stuff on my own. Starting off with this SDL game.

**Comment by Ralex86** [comment]
btwn I remember struggling a lot about ladders detection in this project... can you tell me what you think about it. Falling when you dont press the up arrow is pretty annoying imo ... at the time I was thinking about activate/desactive gravity. Wasn't that easy

**Comment by nidhhoggr** [comment]
Lets put it in a separate issue.

**Comment by Ralex86** [comment]
Cool SDL2 is pretty simple and straightforward ...but it has been a while I didn't code something in C/SDL

**Comment by Ralex86** [comment]
I do calculuus fortran program now haha

**Comment by Ralex86** [comment]
another thing, I saw somewhere you are also a web developper : 
check this other project : https://www.youtube.com/watch?v=n-vuHJ4g3rg
a collaborative plateform, a facebook like website where you can share scientific stuff and write equations etc...

**Comment by Ralex86** [comment]
and for screenshots https://www.facebook.com/pantah.fr/

**Comment by Ralex86** [comment]
https://www.facebook.com/pantah.fr/photos/a.242697209478293.1073741830.103818110032871/242697259478288/?type=3&theater

**Comment by nidhhoggr** [comment]
Cool I'll check it out. Yeah I skipped a lot of math in school and cut to the chase hence: software development. Now I have to learn all the maths on my own. Software development pays the bills but it's boring.

**Comment by nidhhoggr** [comment]
See #7 regarding climbing abilities.

**Comment by nidhhoggr** [comment]
I just watched that video, looks pretty cool but definitely heavy on frontend libraries. I am more of a serverside/devops programmer. I can do full stack but frontend bores me. And as of lately all development (back and front end) bores me in general.

**Comment by Ralex86** [comment]
don't be fooled by the graphical aspect of the ting there are a lot of back end programming in this project trust me :-)  we did our own css framework and we didn't use any javascript libraries or plugin by the way. we used websocket which is a pretty interesting techno

**Comment by nidhhoggr** [comment]
Cool. I have been more interested in C programming lately for recreational coding. That is why I started working on this. I am also interested in 2.5D games. I was looking into fifengine platform which is also written in C. What are you guys using for the backend?
